name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install python packages
      run: pip install -r requirements.txt pyinstaller
    - name: package pyinstaller
      run: pyinstaller --noconsole --noconfirm --distpath resources app.py --collect-all pymatgen --collect-all OgreInterface --collect-all spglib
    - uses: actions/upload-artifact@v2
      with:
        path: resources/*
    - name: install dependencies
      run: yarn install --immutable --immutable-cache --check-cache
    - name: build package
      run: yarn make
